server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://Mysql@localhost:3306/anime
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true;